apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: webapi-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: webapi-route
spec:
  parentRefs:
    - name: webapi-gateway
  rules:
    - matches:
        - path:
            type: Exact
            value: /version
      backendRefs:
        - name: webapi
          port: 80
