apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapi
  namespace: service-mesh
spec:
  hosts:
    - webapi
  http:
    - route:
        - destination:
            host: webapi
            subset: v1
          weight: 50
        - destination:
            host: webapi
            subset: v2
          weight: 50
